services:
  # Container - TeamSpeak 6 Server
  teamspeak:
    image: teamspeaksystems/teamspeak6-server:latest
    container_name: Teamspeak6-Server
    user: "1026:100"
    ports:
      # NAS | Container
      - "9987:9987/udp"     # Voice Port
      - "30033:30033/tcp"   # File Transfer
      #- "10080:10080/tcp"   # Web Query
    environment:
      - TZ=America/New_York
      - TSSERVER_LICENSE_ACCEPTED=accept
    volumes:
      # NAS | Container
      - /volume1/docker/Containers/TeamSpeak6/data:/var/tsserver
    restart: unless-stopped